spring.application.name=A3HoangaTongVietDuc_SE18D04

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FUMiniHotelDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# STAFF ACCOUNT (FROM PROPERTIES)
# ===============================
staff.email=staff@gmail.com
staff.password=123456
